# Generated by Django 5.1.7 on 2025-04-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingcalls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='casting',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='casting',
            name='style',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='casting',
            name='submission_link',
            field=models.CharField(default='', max_length=350),
        ),
    ]
