# Generated by Django 5.1.7 on 2025-04-24 19:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('castingcalls', '0004_calendar'), ('castingcalls', '0005_calendar_is_public'), ('castingcalls', '0006_calendar_name'), ('castingcalls', '0007_alter_casting_is_published_and_more'), ('castingcalls', '0008_alter_casting_is_published'), ('castingcalls', '0009_alter_calendar_castings'), ('castingcalls', '0010_alter_calendar_castings'), ('castingcalls', '0011_alter_casting_producer_alter_casting_producer_name_and_more'), ('castingcalls', '0012_alter_casting_producer_alter_casting_producer_name_and_more')]

    dependencies = [
        ('castingcalls', '0003_casting_producer_name_casting_production_company_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='casting',
            name='submission_link',
            field=models.CharField(max_length=350),
        ),
        migrations.AlterField(
            model_name='casting',
            name='is_published',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('castings', models.ManyToManyField(blank=True, to='castingcalls.casting')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('is_public', models.BooleanField(default=False)),
                ('name', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='casting',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='casting',
            name='producer_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='casting',
            name='production_company',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
