# Generated by Django 5.1.7 on 2025-04-24 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('castingcalls', '0004_calendar_squashed_0012_alter_casting_producer_alter_casting_producer_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
